### ISSUE TITLE
folium map not displaying

### ISSUE THREAD

**Issue by slobotsky** [slobotsky/brianslobotsky_MnM4SDS_project#1]
In [my term project notebook](https://github.com/slobotsky/brianslobotsky_MnM4SDS_project/blob/master/termproject.ipynb), this section of code, going from a geodataframe to a geojson and displaying it with folium, gives a blank output:

`gdf_new.to_file("output.json", driver="GeoJSON")`

`m = folium.Map(location=[39.8, -98.5], zoom_start = 2)`
`folium.GeoJson("output.json").add_to(m)`
`m`

Any help is appreciated. Thank you

**Comment by TaylorOshan** [comment]
I think you need to name your file ``” output. geojson” `` rather than `` "output.json” ``.

If that does not work then you might take a look at [this link](https://stackoverflow.com/questions/42107268/geojson-data-not-displaying-in-python-folium-map) for some other suggestions.

**Comment by slobotsky** [comment]
I've tried output.geojson and output.json, neither worked.

I found that link too, and I tried using folium's TopoJson but I don't know how to identify what the "object_path" is within the .geojson file.

**Comment by TaylorOshan** [comment]
Have you tried rendering the data any other way? try copying and pasting
into
https://www.townsendjennings.com/geo/#2/24.9/23.9

**Comment by TaylorOshan** [comment]
When you create the new df I think you need to reassign the geometry

**Comment by slobotsky** [comment]
Is it possible the issue is the size of the file, which is crashing the display? The output is ~31 mb

**Comment by TaylorOshan** [comment]
yes could be - try selecting a single feature and mapping that.

**Comment by slobotsky** [comment]
Yeah, last night I changed the output so that the .geojson file doesn't contain counties with 0 values. It cut down the size of the file and displayed correctly when I read it into folium. Thanks for the help!
